# Limpieza y selección de datos pertinentes para el EDA

***Comenzamos con la importación de archivos y su respectivo tratamiento para la mejora del manejo de datos***

In [3]:

import pandas as pd
import warnings
warnings.filterwarnings('ignore')

***Abrimos y procedemos a limpiar el archivo csv : "Penetracion de Internet fijo,accesos cada 100 hogares"***

In [4]:
df1 = pd.read_csv('PI_DA\Datos\csv\Acceso_hogares.csv', sep=';')

In [5]:
df1['Provincia'] = df1['Provincia'].astype('category')

In [6]:
df1.info

<bound method DataFrame.info of       Año  Trimestre            Provincia  Accesos por cada 100 hogares
0    2022          4         Buenos Aires                     78.940000
1    2022          4      Capital Federal                    122.730000
2    2022          4            Catamarca                     65.770000
3    2022          4                Chaco                     43.620000
4    2022          4               Chubut                     85.570000
..    ...        ...                  ...                           ...
859  2014          1           Santa Cruz                     28.939093
860  2014          1             Santa Fe                     47.847663
861  2014          1  Santiago Del Estero                     16.309924
862  2014          1     Tierra Del Fuego                     63.965926
863  2014          1              Tucumán                     33.420975

[864 rows x 4 columns]>

In [7]:
#Revisamos los nulos del dataframe 1
df1.isna().sum()

Año                             0
Trimestre                       0
Provincia                       0
Accesos por cada 100 hogares    0
dtype: int64

***Continuamos con Internet accesos por tecnología***

In [8]:
df2 = pd.read_excel('PI_DA/Datos/xlsx/Internet_Accesos-por-tecnologia.xlsx')

In [9]:
df2

,Año,Trimestre,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total,Periodo
0,2022,4,1315373,6037457,3060575,572969,221740,11208114,Oct-Dic 2022
1,2022,3,1395277,6031970,2871541,557110,235230,11091128,Jul-Sept 2022
2,2022,2,1468333,5979214,2723285,556243,231609,10958684,Abr-Jun 2022
3,2022,1,1533240,6073426,2219533,545814,251996,10624009,Ene-Mar 2022
4,2021,4,1657615,5984240,2072236,523107,252596,10489794,Oct-Dic 2021
5,2021,3,1950631,5826257,1566048,492415,250190,10085541,Jul-Sept 2021
6,2021,2,2018587,5641731,1472246,476968,253552,9863084,Abr-Jun 2021
7,2021,1,2175211,5424782,1362976,434548,250455,9647972,Ene-Mar 2021
8,2020,4,2213949,5371824,1311199,421554,253036,9571562,Oct-Dic 2020
9,2020,3,2263889,5259351,1170879,413259,248821,9356199,Jul-Sept 2020
10,2020,2,2295533,5005115,1106725,376667,247016,9031056,Abr-Jun 2020
11,2020,1,2299457,4903674,1047817,352333,209145,8812426,Ene-Mar 2020
12,2019,4,2414575,4883869,941295,340144,213298,8793181,Oct-Dic 2019
13,2019,3,2909805,4800091,852221,338241,264326,9164684,Jul-Sept 2019
14,2019,2,2990457,4635575,760794,308027,265328,8960181,Abr-Jun 2019
15,2019,1,3132789,4435439,637099,276419,166389,8648135,Ene-Mar 2019
16,2018,4,3329027,4313831,388013,264299,178485,8473655,Oct-Dic 2018
17,2018,3,3521447,4238171,247366,246181,93870,8347035,Jul-Sept 2018
18,2018,2,3557216,4038141,226285,194267,94535,8110444,Abr-Jun 2018
19,2018,1,3574294,3981129,217460,165300,98870,8037053,Ene-Mar 2018
20,2017,4,3584311,3818157,211425,155775,100554,7870222,Oct-Dic 2017
21,2017,3,3622575,3670221,193964,106443,131740,7724943,Jul-Sept 2017
22,2017,2,3723518,3383434,180777,85813,56122,7429664,Abr-Jun 2017
23,2017,1,3708898,3276251,180146,84813,55746,7305854,Ene-Mar 2017
24,2016,4,3722794,3210602,178070,85119,55088,7251673,Oct-Dic 2016
25,2016,3,3776442,3124855,169898,81455,54300,7206950,Jul-Sept 2016
26,2016,2,3782085,3035272,167788,85452,59482,7130079,Abr-Jun 2016
27,2016,1,3792493,2806359,164371,85370,58763,6907356,Ene-Mar 2016
28,2015,4,3803024,2898226,139187,85726,58668,6984831,Oct-Dic 2015
29,2015,3,3788696,2840203,162663,84530,58976,6935068,Jul-Sept 2015
30,2015,2,3767821,2756294,150839,82077,59157,6816188,Abr-Jun 2015
31,2015,1,3756153,2668248,168188,79098,66045,6737732,Ene-Mar 2015
32,2014,4,3764038,2536219,149682,76984,71573,6598496,Oct-Dic 2014
33,2014,3,3714764,2569868,155494,85096,70049,6595271,Jul-Sept 2014
34,2014,2,3708882,2461670,149363,72405,72148,6464468,Abr-Jun 2014
35,2014,1,3697066,2407330,150323,70749,72930,6398398,Ene-Mar 2014

In [10]:
#Sacamos la columna período
def clean_data(df2):   
    df2 = df2.drop(columns=['Periodo'])
    return df2

df2_clean = clean_data(df2.copy())
df2_clean.head()

,Año,Trimestre,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
0,2022,4,1315373,6037457,3060575,572969,221740,11208114
1,2022,3,1395277,6031970,2871541,557110,235230,11091128
2,2022,2,1468333,5979214,2723285,556243,231609,10958684
3,2022,1,1533240,6073426,2219533,545814,251996,10624009
4,2021,4,1657615,5984240,2072236,523107,252596,10489794

***Internet accesos por velocidad por localidad***

In [11]:
df3 = pd.read_excel('PI_DA/Datos/xlsx/Internet_Accesos-por-velocidad_por loc.xlsx')

In [12]:
df3.head()

,Provincia,Partido,Localidad,Link Indec,Otros,"0,256 Mbps","0,375 Mbps","0,5 Mbps","0,512 Mbps","0,625 Mbps",...,600 Mbps,680 Mbps,700 Mbps,800 Mbps,850 Mbps,900 Mbps,950 Mbps,1000 Mbps,1024 Mbps,Total general
0,BUENOS AIRES,25 de Mayo,25 de Mayo,6854100,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6208.0
1,BUENOS AIRES,25 de Mayo,Agustín Mosconi,6854010,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0
2,BUENOS AIRES,25 de Mayo,Del Valle,6854020,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,192.0
3,BUENOS AIRES,25 de Mayo,Ernestina,6854030,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.0
4,BUENOS AIRES,25 de Mayo,Gobernador Ugarte,6854040,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181.0

In [13]:

def clean_data(df3):
    #Convertimos a texto capital
    df3['Provincia'] = df3['Provincia'].str.title()
    #Reemplazamos por 0 los valores mal designados
    df3 = df3.fillna({'Otros': 0, '0,256 Mbps': 0, '0,375 Mbps': 0, '0,5 Mbps': 0, '0,512 Mbps': 0, '0,625 Mbps': 0, '0,75 Mbps': 0, '1 Mbps': 0, '1,25 Mbps': 0, '1,5 Mbps': 0, '2 Mbps': 0, '2,2 Mbps': 0, '2,5 Mbps': 0, '3 Mbps': 0, '3,3 Mbps': 0, '3,5 Mbps': 0, '4 Mbps': 0, '4,5 Mbps': 0, '5 Mbps': 0, '6 Mbps': 0, '6,4 Mbps': 0, '7 Mbps': 0, '7,5 Mbps': 0, '8 Mbps': 0, '9 Mbps': 0, '10 Mbps': 0, '10,2 Mbps': 0, '11 Mbps': 0, '12 Mbps': 0, '12,3 Mbps': 0, '13 Mbps': 0, '14 Mbps': 0, '15 Mbps': 0, '16 Mbps': 0, '17 Mbps': 0, '18 Mbps': 0, '20 Mbps': 0, '20,5 Mbps': 0, '21 Mbps': 0, '22 Mbps': 0, '23 Mbps': 0, '24 Mbps': 0, '25 Mbps': 0, '25,1 Mbps': 0, '25,5 Mbps': 0, '26 Mbps': 0, '27 Mbps': 0, '30 Mbps': 0, '31 Mbps': 0, '32 Mbps': 0, '34 Mbps': 0, '35 Mbps': 0, '36 Mbps': 0, '38 Mbps': 0, '39 Mbps': 0, '40 Mbps': 0, '41 Mbps': 0, '45 Mbps': 0, '46 Mbps': 0, '48 Mbps': 0, '49 Mbps': 0, '50 Mbps': 0, '50,1 Mbps': 0, '50,25 Mbps': 0, '51 Mbps': 0, '55 Mbps': 0, '58 Mbps': 0, '59 Mbps': 0, '60 Mbps': 0, '61 Mbps': 0, '62 Mbps': 0, '64 Mbps': 0, '65 Mbps': 0, '66 Mbps': 0, '70 Mbps': 0, '75 Mbps': 0, '78 Mbps': 0, '80 Mbps': 0, '83 Mbps': 0, '85 Mbps': 0, '90 Mbps': 0, '92 Mbps': 0, '95 Mbps': 0, '100 Mbps': 0, '100,25 Mbps': 0, '110 Mbps': 0, '120 Mbps': 0, '122 Mbps': 0, '125 Mbps': 0, '126 Mbps': 0, '130 Mbps': 0, '140 Mbps': 0, '150 Mbps': 0, '157 Mbps': 0, '158 Mbps': 0, '160 Mbps': 0, '164 Mbps': 0, '165 Mbps': 0, '180 Mbps': 0, '200 Mbps': 0, '212 Mbps': 0, '220 Mbps': 0, '225 Mbps': 0, '234 Mbps': 0, '240 Mbps': 0, '250 Mbps': 0, '256 Mbps': 0, '275 Mbps': 0, '300 Mbps': 0, '320 Mbps': 0, '325 Mbps': 0, '330 Mbps': 0, '340 Mbps': 0, '400 Mbps': 0, '450 Mbps': 0, '480 Mbps': 0, '500 Mbps': 0, '512 Mbps': 0, '520 Mbps': 0, '540 Mbps': 0, '600 Mbps': 0, '680 Mbps': 0, '700 Mbps': 0, '800 Mbps': 0, '850 Mbps': 0, '900 Mbps': 0, '950 Mbps': 0, '1000 Mbps': 0, '1024 Mbps': 0, 'Total general': 0})
    return df3

df3 = clean_data(df3)
df3.head()

,Provincia,Partido,Localidad,Link Indec,Otros,"0,256 Mbps","0,375 Mbps","0,5 Mbps","0,512 Mbps","0,625 Mbps",...,600 Mbps,680 Mbps,700 Mbps,800 Mbps,850 Mbps,900 Mbps,950 Mbps,1000 Mbps,1024 Mbps,Total general
0,Buenos Aires,25 de Mayo,25 de Mayo,6854100,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6208.0
1,Buenos Aires,25 de Mayo,Agustín Mosconi,6854010,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,59.0
2,Buenos Aires,25 de Mayo,Del Valle,6854020,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,192.0
3,Buenos Aires,25 de Mayo,Ernestina,6854030,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,66.0
4,Buenos Aires,25 de Mayo,Gobernador Ugarte,6854040,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,181.0

***Abrimos el archivo Internet accesos por velocidad sin rangos***

In [14]:
df4 =pd.read_excel('PI_DA/Datos/xlsx/Internet_Accesos-por-velocidad_provincia_sin rangos.xlsx')

In [15]:
df4

,Año,Trimestre,Provincia,Otros,"0,256 Mbps","0,375 Mbps","0,625 Mbps","0,5 Mbps","0,512 Mbps","0,75 Mbps",...,2048 Mbps,2529 Mbps,3072 Mbps,4000 Mbps,5000 Mbps,5125 Mbps,6000 Mbps,7000 Mbps,8000 Mbps,10000 Mbps
0,2022.0,4.0,Buenos Aires,97634.0,18.0,0.0,0.0,28724.0,192.0,4611.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022.0,4.0,Capital Federal,106772.0,31.0,0.0,0.0,451.0,34.0,1307.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2022.0,4.0,Catamarca,2280.0,0.0,0.0,0.0,34.0,37.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2022.0,4.0,Chaco,3909.0,0.0,225.0,111.0,234.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2022.0,4.0,Chubut,20026.0,8.0,0.0,0.0,69.0,32.0,836.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,2017.0,4.0,Santa Fe,14119.0,0.0,0.0,0.0,3109.0,0.0,7637.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
501,2017.0,4.0,Santiago Del Estero,0.0,0.0,0.0,0.0,41.0,0.0,909.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
502,2017.0,4.0,Tierra Del Fuego,0.0,0.0,0.0,0.0,6.0,0.0,282.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
503,2017.0,4.0,Tucumán,0.0,0.0,0.0,0.0,105.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#Reemplazamos valores 

def clean_data(df4):
    df4 = df4.fillna({'0,256 Mbps': 0, '10000 Mbps': 0, '8000 Mbps': 0, '7000 Mbps': 0, '6000 Mbps': 0, '5125 Mbps': 0, '5000 Mbps': 0, '4000 Mbps': 0, '3072 Mbps': 0, '2529 Mbps': 0, '2048 Mbps': 0, '2000 Mbps': 0, '1536 Mbps': 0, '1075 Mbps': 0, '1024 Mbps': 0, '1000 Mbps': 0, '950 Mbps': 0, '945 Mbps': 0, '900 Mbps': 0, '850 Mbps': 0, '800 Mbps': 0, '768 Mbps': 0, '700 Mbps': 0, '680 Mbps': 0, '640 Mbps': 0, '600 Mbps': 0, '540 Mbps': 0, '520 Mbps': 0, '512 Mbps': 0, '500 Mbps': 0, '480 Mbps': 0, '473 Mbps': 0, '450 Mbps': 0, '400 Mbps': 0, '384 Mbps': 0, '380 Mbps': 0, '350 Mbps': 0, '340 Mbps': 0, '330 Mbps': 0, '325 Mbps': 0, '320 Mbps': 0, '300 Mbps': 0, '275 Mbps': 0, '270 Mbps': 0, '256 Mbps': 0, '250 Mbps': 0, '240 Mbps': 0, '234 Mbps': 0, '225 Mbps': 0, '220 Mbps': 0, '212 Mbps': 0, '203 Mbps': 0, '200 Mbps': 0, '180 Mbps': 0, '165 Mbps': 0, '164 Mbps': 0, '160 Mbps': 0, '158 Mbps': 0, '150 Mbps': 0, '157 Mbps': 0, '145 Mbps': 0, '140 Mbps': 0, '137 Mbps': 0, '134 Mbps': 0, '131 Mbps': 0, '130 Mbps': 0, '128 Mbps': 0, '127 Mbps': 0, '126 Mbps': 0, '125 Mbps': 0, '122 Mbps': 0, '120 Mbps': 0, '110 Mbps': 0, '109 Mbps': 0, '105 Mbps': 0, '100,25 Mbps': 0, '100 Mbps': 0, '98 Mbps': 0, '95 Mbps': 0, '92 Mbps': 0, '91 Mbps': 0, '90 Mbps': 0, '85 Mbps': 0, '84 Mbps': 0, '86 Mbps': 0, '82 Mbps': 0, '83 Mbps': 0, '81 Mbps': 0, '80 Mbps': 0, '78 Mbps': 0, '77 Mbps': 0, '75 Mbps': 0, '71 Mbps': 0, '70 Mbps': 0, '68 Mbps': 0, '67 Mbps': 0, '66 Mbps': 0, '65 Mbps': 0, '64 Mbps': 0, '63 Mbps': 0, '62 Mbps': 0, '61 Mbps': 0, '60 Mbps': 0, '59 Mbps': 0, '58 Mbps': 0, '56 Mbps': 0, '55 Mbps': 0, '54 Mbps': 0, '52 Mbps': 0, '50,25 Mbps': 0, '51 Mbps': 0, '50,1 Mbps': 0, '49 Mbps': 0, '50 Mbps': 0, '48 Mbps': 0, '47 Mbps': 0, '46 Mbps': 0, '45 Mbps': 0, '41 Mbps': 0, '40 Mbps': 0, '39 Mbps': 0, '38 Mbps': 0, '37 Mbps': 0, '36 Mbps': 0, '35 Mbps': 0, '34 Mbps': 0, '32 Mbps': 0, '31 Mbps': 0, '30 Mbps': 0, '29 Mbps': 0, '28 Mbps': 0, '27 Mbps': 0, '26 Mbps': 0, '25,5 Mbps': 0, '25,11 Mbps': 0, '25,1 Mbps': 0, '25 Mbps': 0, '24 Mbps': 0, '23 Mbps': 0, '22 Mbps': 0, '21 Mbps': 0, '20,5 Mbps': 0, '20 Mbps': 0, '19 Mbps': 0, '18 Mbps': 0, '17 Mbps': 0, '16 Mbps': 0, '15 Mbps': 0, '14 Mbps': 0, '13 Mbps': 0, '12,3 Mbps': 0, '12 Mbps': 0, '11 Mbps': 0, '10,6 Mbps': 0, '10,2 Mbps': 0, '10 Mbps': 0, '9 Mbps': 0, '8 Mbps': 0, '7,5 Mbps': 0, '7 Mbps': 0, '6,4 Mbps': 0, '6 Mbps': 0, '5 Mbps': 0, '4,5 Mbps': 0, '4 Mbps': 0, '3,5 Mbps': 0, '3,3 Mbps': 0, '3,2 Mbps': 0, '3 Mbps': 0, '6,7 Mbps': 0, '2,2 Mbps': 0, '2 Mbps': 0, '1,5 Mbps': 0, '1,25 Mbps': 0, '1,2 Mbps': 0, '1 Mbps': 0, '0,75 Mbps': 0, '0,512 Mbps': 0, '0,5 Mbps': 0, '0,625 Mbps': 0, '0,375 Mbps': 0})
    #Cambiamos los valores a int64
    df4 = df4.astype({'0,256 Mbps': 'int64', '0,375 Mbps': 'int64', '0,625 Mbps': 'int64', '0,5 Mbps': 'int64', '0,512 Mbps': 'int64', '0,75 Mbps': 'int64', '1 Mbps': 'int64', '1,2 Mbps': 'int64', '1,25 Mbps': 'int64', '1,5 Mbps': 'int64', '2 Mbps': 'int64', '2,2 Mbps': 'int64', '2,5 Mbps': 'int64', '6,7 Mbps': 'int64', '3 Mbps': 'int64', '3,2 Mbps': 'int64', '3,3 Mbps': 'int64', '3,5 Mbps': 'int64', '4 Mbps': 'int64', '4,5 Mbps': 'int64', '5 Mbps': 'int64', '6 Mbps': 'int64', '6,4 Mbps': 'int64', '7 Mbps': 'int64', '7,5 Mbps': 'int64', '8 Mbps': 'int64', '9 Mbps': 'int64', '10 Mbps': 'int64', '10,2 Mbps': 'int64', '10,6 Mbps': 'int64', '11 Mbps': 'int64', '12 Mbps': 'int64', '12,3 Mbps': 'int64', '13 Mbps': 'int64', '14 Mbps': 'int64', '15 Mbps': 'int64', '16 Mbps': 'int64', '17 Mbps': 'int64', '18 Mbps': 'int64', '19 Mbps': 'int64', '20 Mbps': 'int64', '20,5 Mbps': 'int64', '21 Mbps': 'int64', '22 Mbps': 'int64', '23 Mbps': 'int64', '24 Mbps': 'int64', '25 Mbps': 'int64', '25,1 Mbps': 'int64', '25,11 Mbps': 'int64', '25,5 Mbps': 'int64', '26 Mbps': 'int64', '27 Mbps': 'int64', '28 Mbps': 'int64', '29 Mbps': 'int64', '30 Mbps': 'int64', '31 Mbps': 'int64', '32 Mbps': 'int64', '34 Mbps': 'int64', '35 Mbps': 'int64', '36 Mbps': 'int64', '37 Mbps': 'int64', '38 Mbps': 'int64', '39 Mbps': 'int64', '40 Mbps': 'int64', '41 Mbps': 'int64', '45 Mbps': 'int64', '46 Mbps': 'int64', '47 Mbps': 'int64', '48 Mbps': 'int64', '49 Mbps': 'int64', '50 Mbps': 'int64', '50,1 Mbps': 'int64', '51 Mbps': 'int64', '50,25 Mbps': 'int64', '52 Mbps': 'int64', '54 Mbps': 'int64', '55 Mbps': 'int64', '56 Mbps': 'int64', '58 Mbps': 'int64', '59 Mbps': 'int64', '60 Mbps': 'int64', '61 Mbps': 'int64', '62 Mbps': 'int64', '63 Mbps': 'int64', '64 Mbps': 'int64', '65 Mbps': 'int64', '66 Mbps': 'int64', '67 Mbps': 'int64', '68 Mbps': 'int64', '70 Mbps': 'int64', '71 Mbps': 'int64', '75 Mbps': 'int64', '77 Mbps': 'int64', '78 Mbps': 'int64', '80 Mbps': 'int64', '81 Mbps': 'int64', '83 Mbps': 'int64', '82 Mbps': 'int64', '86 Mbps': 'int64', '84 Mbps': 'int64', '85 Mbps': 'int64', '90 Mbps': 'int64', '91 Mbps': 'int64', '92 Mbps': 'int64', '95 Mbps': 'int64', '98 Mbps': 'int64', '100 Mbps': 'int64', '100,25 Mbps': 'int64', '105 Mbps': 'int64', '109 Mbps': 'int64', '110 Mbps': 'int64', '120 Mbps': 'int64', '122 Mbps': 'int64', '125 Mbps': 'int64', '126 Mbps': 'int64', '127 Mbps': 'int64', '128 Mbps': 'int64', '130 Mbps': 'int64', '131 Mbps': 'int64', '134 Mbps': 'int64', '137 Mbps': 'int64', '140 Mbps': 'int64', '145 Mbps': 'int64', '150 Mbps': 'int64', '157 Mbps': 'int64', '158 Mbps': 'int64', '160 Mbps': 'int64', '164 Mbps': 'int64', '165 Mbps': 'int64', '180 Mbps': 'int64', '200 Mbps': 'int64', '203 Mbps': 'int64', '212 Mbps': 'int64', '220 Mbps': 'int64', '225 Mbps': 'int64', '234 Mbps': 'int64', '240 Mbps': 'int64', '250 Mbps': 'int64', '256 Mbps': 'int64', '270 Mbps': 'int64', '275 Mbps': 'int64', '300 Mbps': 'int64', '320 Mbps': 'int64', '325 Mbps': 'int64', '330 Mbps': 'int64', '340 Mbps': 'int64', '350 Mbps': 'int64', '380 Mbps': 'int64', '384 Mbps': 'int64', '400 Mbps': 'int64', '450 Mbps': 'int64', '473 Mbps': 'int64', '480 Mbps': 'int64', '500 Mbps': 'int64', '512 Mbps': 'int64', '520 Mbps': 'int64', '540 Mbps': 'int64', '600 Mbps': 'int64', '640 Mbps': 'int64', '680 Mbps': 'int64', '700 Mbps': 'int64', '768 Mbps': 'int64', '800 Mbps': 'int64', '850 Mbps': 'int64', '900 Mbps': 'int64', '945 Mbps': 'int64', '950 Mbps': 'int64', '1000 Mbps': 'int64', '1024 Mbps': 'int64', '1075 Mbps': 'int64', '1536 Mbps': 'int64', '2000 Mbps': 'int64', '2048 Mbps': 'int64', '2529 Mbps': 'int64', '3072 Mbps': 'int64', '4000 Mbps': 'int64', '5000 Mbps': 'int64', '5125 Mbps': 'int64', '6000 Mbps': 'int64', '7000 Mbps': 'int64', '8000 Mbps': 'int64', '10000 Mbps': 'int64'})
    #Dropeamos las filas en la columna Año
    df4 = df4.dropna(subset=['Año'])
    #Cambiamos el tipo de columna de año y velocidades a int64
    df4 = df4.astype({'Año': 'int64','0,256 Mbps': 'int64', '0,375 Mbps': 'int64', '0,625 Mbps': 'int64', '0,5 Mbps': 'int64', '0,512 Mbps': 'int64', '0,75 Mbps': 'int64', '1 Mbps': 'int64', '1,2 Mbps': 'int64', '1,25 Mbps': 'int64', '1,5 Mbps': 'int64', '2 Mbps': 'int64', '2,2 Mbps': 'int64', '2,5 Mbps': 'int64', '6,7 Mbps': 'int64', '3 Mbps': 'int64', '3,2 Mbps': 'int64', '3,3 Mbps': 'int64', '3,5 Mbps': 'int64', '4 Mbps': 'int64', '4,5 Mbps': 'int64', '5 Mbps': 'int64', '6 Mbps': 'int64', '6,4 Mbps': 'int64', '7 Mbps': 'int64', '7,5 Mbps': 'int64', '8 Mbps': 'int64', '9 Mbps': 'int64', '10 Mbps': 'int64', '10,2 Mbps': 'int64', '10,6 Mbps': 'int64', '11 Mbps': 'int64', '12 Mbps': 'int64', '12,3 Mbps': 'int64', '13 Mbps': 'int64', '14 Mbps': 'int64', '15 Mbps': 'int64', '16 Mbps': 'int64', '17 Mbps': 'int64', '18 Mbps': 'int64', '19 Mbps': 'int64', '20 Mbps': 'int64', '20,5 Mbps': 'int64', '21 Mbps': 'int64', '22 Mbps': 'int64', '23 Mbps': 'int64', '24 Mbps': 'int64', '25 Mbps': 'int64', '25,1 Mbps': 'int64', '25,11 Mbps': 'int64', '25,5 Mbps': 'int64', '26 Mbps': 'int64', '27 Mbps': 'int64', '28 Mbps': 'int64', '29 Mbps': 'int64', '30 Mbps': 'int64', '31 Mbps': 'int64', '32 Mbps': 'int64', '34 Mbps': 'int64', '35 Mbps': 'int64', '36 Mbps': 'int64', '37 Mbps': 'int64', '38 Mbps': 'int64', '39 Mbps': 'int64', '40 Mbps': 'int64', '41 Mbps': 'int64', '45 Mbps': 'int64', '46 Mbps': 'int64', '47 Mbps': 'int64', '48 Mbps': 'int64', '49 Mbps': 'int64', '50 Mbps': 'int64', '50,1 Mbps': 'int64', '51 Mbps': 'int64', '50,25 Mbps': 'int64', '52 Mbps': 'int64', '54 Mbps': 'int64', '55 Mbps': 'int64', '56 Mbps': 'int64', '58 Mbps': 'int64', '59 Mbps': 'int64', '60 Mbps': 'int64', '61 Mbps': 'int64', '62 Mbps': 'int64', '63 Mbps': 'int64', '64 Mbps': 'int64', '65 Mbps': 'int64', '66 Mbps': 'int64', '67 Mbps': 'int64', '68 Mbps': 'int64', '70 Mbps': 'int64', '71 Mbps': 'int64', '75 Mbps': 'int64', '77 Mbps': 'int64', '78 Mbps': 'int64', '80 Mbps': 'int64', '81 Mbps': 'int64', '83 Mbps': 'int64', '82 Mbps': 'int64', '86 Mbps': 'int64', '84 Mbps': 'int64', '85 Mbps': 'int64', '90 Mbps': 'int64', '91 Mbps': 'int64', '92 Mbps': 'int64', '95 Mbps': 'int64', '98 Mbps': 'int64', '100 Mbps': 'int64', '100,25 Mbps': 'int64', '105 Mbps': 'int64', '109 Mbps': 'int64', '110 Mbps': 'int64', '120 Mbps': 'int64', '122 Mbps': 'int64', '125 Mbps': 'int64', '126 Mbps': 'int64', '127 Mbps': 'int64', '128 Mbps': 'int64', '130 Mbps': 'int64', '131 Mbps': 'int64', '134 Mbps': 'int64', '137 Mbps': 'int64', '140 Mbps': 'int64', '145 Mbps': 'int64', '150 Mbps': 'int64', '157 Mbps': 'int64', '158 Mbps': 'int64', '160 Mbps': 'int64', '164 Mbps': 'int64', '165 Mbps': 'int64', '180 Mbps': 'int64', '200 Mbps': 'int64', '203 Mbps': 'int64', '212 Mbps': 'int64', '220 Mbps': 'int64', '225 Mbps': 'int64', '234 Mbps': 'int64', '240 Mbps': 'int64', '250 Mbps': 'int64', '256 Mbps': 'int64', '270 Mbps': 'int64', '275 Mbps': 'int64', '300 Mbps': 'int64', '320 Mbps': 'int64', '325 Mbps': 'int64', '330 Mbps': 'int64', '340 Mbps': 'int64', '350 Mbps': 'int64', '380 Mbps': 'int64', '384 Mbps': 'int64', '400 Mbps': 'int64', '450 Mbps': 'int64', '473 Mbps': 'int64', '480 Mbps': 'int64', '500 Mbps': 'int64', '512 Mbps': 'int64', '520 Mbps': 'int64', '540 Mbps': 'int64', '600 Mbps': 'int64', '640 Mbps': 'int64', '680 Mbps': 'int64', '700 Mbps': 'int64', '768 Mbps': 'int64', '800 Mbps': 'int64', '850 Mbps': 'int64', '900 Mbps': 'int64', '945 Mbps': 'int64', '950 Mbps': 'int64', '1000 Mbps': 'int64', '1024 Mbps': 'int64', '1075 Mbps': 'int64', '1536 Mbps': 'int64', '2000 Mbps': 'int64', '2048 Mbps': 'int64', '2529 Mbps': 'int64', '3072 Mbps': 'int64', '4000 Mbps': 'int64', '5000 Mbps': 'int64', '5125 Mbps': 'int64', '6000 Mbps': 'int64', '7000 Mbps': 'int64', '8000 Mbps': 'int64', '10000 Mbps': 'int64'})
    return df4

df4 = clean_data(df4.copy())
df4.head()

,Año,Trimestre,Provincia,Otros,"0,256 Mbps","0,375 Mbps","0,625 Mbps","0,5 Mbps","0,512 Mbps","0,75 Mbps",...,2048 Mbps,2529 Mbps,3072 Mbps,4000 Mbps,5000 Mbps,5125 Mbps,6000 Mbps,7000 Mbps,8000 Mbps,10000 Mbps
0,2022,4.0,Buenos Aires,97634.0,18,0,0,28724,192,4611,...,0,0,0,0,0,0,0,0,0,0
1,2022,4.0,Capital Federal,106772.0,31,0,0,451,34,1307,...,0,0,0,0,0,0,0,0,0,0
2,2022,4.0,Catamarca,2280.0,0,0,0,34,37,0,...,0,0,0,0,0,0,0,0,0,0
3,2022,4.0,Chaco,3909.0,0,225,111,234,2,0,...,0,0,0,0,0,0,0,0,0,0
4,2022,4.0,Chubut,20026.0,8,0,0,69,32,836,...,0,0,0,0,0,0,0,0,0,0

In [17]:
df4

,Año,Trimestre,Provincia,Otros,"0,256 Mbps","0,375 Mbps","0,625 Mbps","0,5 Mbps","0,512 Mbps","0,75 Mbps",...,2048 Mbps,2529 Mbps,3072 Mbps,4000 Mbps,5000 Mbps,5125 Mbps,6000 Mbps,7000 Mbps,8000 Mbps,10000 Mbps
0,2022,4.0,Buenos Aires,97634.0,18,0,0,28724,192,4611,...,0,0,0,0,0,0,0,0,0,0
1,2022,4.0,Capital Federal,106772.0,31,0,0,451,34,1307,...,0,0,0,0,0,0,0,0,0,0
2,2022,4.0,Catamarca,2280.0,0,0,0,34,37,0,...,0,0,0,0,0,0,0,0,0,0
3,2022,4.0,Chaco,3909.0,0,225,111,234,2,0,...,0,0,0,0,0,0,0,0,0,0
4,2022,4.0,Chubut,20026.0,8,0,0,69,32,836,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,2017,4.0,Santa Cruz,0.0,0,0,0,68,0,0,...,0,0,0,0,0,0,0,0,0,0
500,2017,4.0,Santa Fe,14119.0,0,0,0,3109,0,7637,...,0,0,0,0,0,0,0,0,0,0
501,2017,4.0,Santiago Del Estero,0.0,0,0,0,41,0,909,...,0,0,0,0,0,0,0,0,0,0
502,2017,4.0,Tierra Del Fuego,0.0,0,0,0,6,0,282,...,0,0,0,0,0,0,0,0,0,0
503,2017,4.0,Tucumán,0.0,0,0,0,105,0,1,...,0,0,0,0,0,0,0,0,0,0

In [18]:
#Definir los rangos
rangos = {
    'HASTA 512 kbps': ['0,256 Mbps', '0,375 Mbps', '0,5 Mbps', '0,512 Mbps'],
    '+ 512 Kbps - 1 Mbps': ['0,75 Mbps', '1 Mbps', '1,2 Mbps', '1,25 Mbps'],
    '+ 1 Mbps - 6 Mbps': ['1,5 Mbps', '2 Mbps', '2,2 Mbps', '2,5 Mbps', '6,7 Mbps', '3 Mbps', '3,2 Mbps', '3,3 Mbps', '3,5 Mbps', '4 Mbps', '4,5 Mbps', '5 Mbps'],
    '+ 6 Mbps - 10 Mbps': ['6 Mbps', '6,4 Mbps', '7 Mbps', '7,5 Mbps', '8 Mbps', '9 Mbps', '10 Mbps', '10,2 Mbps', '10,6 Mbps', '11 Mbps', '12 Mbps', '12,3 Mbps', '13 Mbps', '14 Mbps', '15 Mbps', '16 Mbps', '17 Mbps', '18 Mbps', '19 Mbps', '20 Mbps'],
    '+ 10 Mbps - 20 Mbps': ['20,5 Mbps', '21 Mbps', '22 Mbps', '23 Mbps', '24 Mbps', '25 Mbps', '25,1 Mbps', '25,11 Mbps', '25,5 Mbps', '26 Mbps', '27 Mbps', '28 Mbps', '29 Mbps', '30 Mbps', '31 Mbps', '32 Mbps', '34 Mbps', '35 Mbps', '36 Mbps', '37 Mbps', '38 Mbps', '39 Mbps', '40 Mbps', '41 Mbps', '45 Mbps', '46 Mbps', '47 Mbps', '48 Mbps', '49 Mbps', '50 Mbps', '50,1 Mbps', '51 Mbps', '50,25 Mbps', '52 Mbps'],
    '+ 20 Mbps - 30 Mbps': ['54 Mbps', '55 Mbps', '56 Mbps', '58 Mbps', '59 Mbps', '60 Mbps', '61 Mbps', '62 Mbps', '63 Mbps', '64 Mbps', '65 Mbps', '66 Mbps', '67 Mbps', '68 Mbps', '70 Mbps', '71 Mbps'],
    '+ 30 Mbps': ['75 Mbps', '77 Mbps', '78 Mbps', '80 Mbps', '81 Mbps', '83 Mbps', '82 Mbps', '86 Mbps', '84 Mbps', '85 Mbps', '90 Mbps', '91 Mbps', '92 Mbps', '95 Mbps', '98 Mbps'],
}
#Iterar sobre los rangos y contar la cantidad de velocidades en cada rango
for rango, velocidades in rangos.items():
    df4[rango] = df4[velocidades].sum(axis=1)

#Calcular la columna 'Total'
df4['Total'] = df4.iloc[:, 3:].sum(axis=1)

In [19]:
df4

,Año,Trimestre,Provincia,Otros,"0,256 Mbps","0,375 Mbps","0,625 Mbps","0,5 Mbps","0,512 Mbps","0,75 Mbps",...,8000 Mbps,10000 Mbps,HASTA 512 kbps,+ 512 Kbps - 1 Mbps,+ 1 Mbps - 6 Mbps,+ 6 Mbps - 10 Mbps,+ 10 Mbps - 20 Mbps,+ 20 Mbps - 30 Mbps,+ 30 Mbps,Total
0,2022,4.0,Buenos Aires,97634.0,18,0,0,28724,192,4611,...,0,0,28934,23347,163636,622335,1289104,441360,99071,7462452.0
1,2022,4.0,Capital Federal,106772.0,31,0,0,451,34,1307,...,0,0,516,5096,20243,112066,138065,105173,28414,1961499.0
2,2022,4.0,Catamarca,2280.0,0,0,0,34,37,0,...,0,0,71,315,1165,11217,33510,0,0,117187.0
3,2022,4.0,Chaco,3909.0,0,225,111,234,2,0,...,0,0,461,685,8829,31763,30607,0,0,216008.0
4,2022,4.0,Chubut,20026.0,8,0,0,69,32,836,...,0,0,109,1614,30726,81466,34267,0,0,316941.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,2017,4.0,Santa Cruz,0.0,0,0,0,68,0,0,...,0,0,68,78,11019,18809,4,0,0,59956.0
500,2017,4.0,Santa Fe,14119.0,0,0,0,3109,0,7637,...,0,0,3109,34132,119077,451189,46196,1,1,1325669.0
501,2017,4.0,Santiago Del Estero,0.0,0,0,0,41,0,909,...,0,0,41,3091,28788,36888,34,0,0,137684.0
502,2017,4.0,Tierra Del Fuego,0.0,0,0,0,6,0,282,...,0,0,6,310,9429,21907,0,0,0,63304.0
503,2017,4.0,Tucumán,0.0,0,0,0,105,0,1,...,0,0,105,8164,8185,140124,1303,0,0,320129.0

In [20]:
def clean_data(df4):
    #Cambiamos el tipo de la columna: 'Total'
    df4 = df4.astype({'Total': 'int64'})
    return df4

df4_clean = clean_data(df4.copy())
df4_clean.head()

,Año,Trimestre,Provincia,Otros,"0,256 Mbps","0,375 Mbps","0,625 Mbps","0,5 Mbps","0,512 Mbps","0,75 Mbps",...,8000 Mbps,10000 Mbps,HASTA 512 kbps,+ 512 Kbps - 1 Mbps,+ 1 Mbps - 6 Mbps,+ 6 Mbps - 10 Mbps,+ 10 Mbps - 20 Mbps,+ 20 Mbps - 30 Mbps,+ 30 Mbps,Total
0,2022,4.0,Buenos Aires,97634.0,18,0,0,28724,192,4611,...,0,0,28934,23347,163636,622335,1289104,441360,99071,7462452
1,2022,4.0,Capital Federal,106772.0,31,0,0,451,34,1307,...,0,0,516,5096,20243,112066,138065,105173,28414,1961499
2,2022,4.0,Catamarca,2280.0,0,0,0,34,37,0,...,0,0,71,315,1165,11217,33510,0,0,117187
3,2022,4.0,Chaco,3909.0,0,225,111,234,2,0,...,0,0,461,685,8829,31763,30607,0,0,216008
4,2022,4.0,Chubut,20026.0,8,0,0,69,32,836,...,0,0,109,1614,30726,81466,34267,0,0,316941

In [21]:
df5 = pd.read_excel('PI_DA/Datos/xlsx/Internet_Accesos-por-velocidad.xlsx')

In [22]:
df6 = pd.read_excel('PI_DA/Datos/xlsx/historico_velocidad_internet.xlsx')

In [23]:
df7 = pd.read_excel('PI_DA/Datos/xlsx/Internet_BAF.xlsx')

In [24]:
df8 = pd.read_excel('PI_DA/Datos/xlsx/indicadoresmacro.xlsx')

In [25]:
df9 = pd.read_excel('PI_DA/Datos/xlsx/Internet_Ingresos.xlsx')

In [26]:

def clean_data(df9):
    #Sacamos la columna período
    df9 = df9.drop(columns=['Periodo'])
    return df9

df9_clean = clean_data(df9.copy())
df9_clean.head()

    Año  Trimestre  Ingresos (miles de pesos)
0  2022          4               7.244348e+07
1  2022          3               6.408678e+07
2  2022          2               6.041950e+07
3  2022          1               5.521931e+07
4  2021          4               4.546789e+07

In [27]:

def clean_data(df9_clean):
    #Redondeamos ingresos a 2 decimales
    df9_clean = df9_clean.round({'Ingresos (miles de pesos)': 2})
    return df9_clean

df9_clean_1 = clean_data(df9_clean.copy())
df9_clean_1.head()

    Año  Trimestre  Ingresos (miles de pesos)
0  2022          4                72443482.99
1  2022          3                64086784.33
2  2022          2                60419500.62
3  2022          1                55219313.01
4  2021          4                45467887.17

In [28]:
df1.to_csv('PI_DA/Datos/csv/1.Acceso_hogares.csv', index=False)
df2.to_csv('PI_DA/Datos/csv/2.Accesos por tecnologia.csv', index=False)
df3.to_csv('PI_DA/Datos/csv/3.Acceso a Internet fijo por tecnología y provincia.csv',index=False)
df4.to_csv('PI_DA/Datos/csv/4.Internet_Accesos-por-velocidad_provincia_sin rangos.csv',index=False)
df5.to_csv('PI_DA/Datos/csv/5.Internet_Accesos-por-velocidad.csv',index=False)
df6.to_csv('PI_DA/Datos/csv/6.historico_velocidad_internet.csv',index=False)
df7.to_csv('PI_DA/Datos/csv/7.Internet_BAF.csv',index=False)
df8.to_csv('PI_DA/Datos/csv/8.indicadoresmacro.csv',index=False)
df9.to_csv('PI_DA/Datos/csv/9.Internet_Ingresos.csv',index=False)

KeyboardInterrupt: